version: "3.9"

services:
  user:
    image: cosmtrek/air
    working_dir: /project
    volumes:
      - ./user:/project/
    ports:
      - "3001:8081"
    environment:
      - PORT=8081
      - JEAGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - obs
networks:
  obs:
    driver: bridge
